[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1
